(()=>{
 if(globalThis.__resumeWidget?.version==='0.3.1'&&globalThis.__resumeWidget.runtime===chrome.runtime){globalThis.__resumeWidget.open();return;}
 globalThis.__resumeWidget?.destroy?.();document.getElementById('resume-companion-local')?.remove();
 const host=document.createElement('div');host.id='resume-companion-local';host.style.cssText='all:initial;position:fixed;right:20px;bottom:90px;z-index:2147483646';
 const root=host.attachShadow({mode:'closed'});document.documentElement.append(host);
 root.innerHTML=`<style>:host{all:initial}*{box-sizing:border-box}button,input{font:inherit}button{cursor:pointer;border:0;border-radius:9px;padding:10px 15px;background:#087e70;color:#fff;font-weight:600}button:disabled{background:#c5d7d1;cursor:default}.fab{box-shadow:0 5px 24px #164e4340;padding:14px 20px;font:600 15px 'Microsoft YaHei',sans-serif}.drawer{font:14px/1.6 'Microsoft YaHei',sans-serif;position:fixed;right:16px;top:18px;bottom:18px;width:min(460px,calc(100vw - 32px));background:#f6f9f7;border:1px solid #d7e6df;border-radius:18px;box-shadow:0 10px 60px #17352f33;color:#243e35;display:flex;flex-direction:column;overflow:hidden}.head{padding:20px;background:white;display:flex;justify-content:space-between;align-items:center}.head strong{font-size:18px}.head small{display:block;color:#789187;font-size:11px}.light{background:#eaf2ed;color:#41715d}.body{padding:18px;overflow:auto;flex:1}.actions{display:flex;gap:8px;flex-wrap:wrap}.status{padding:12px 0;color:#537864;white-space:pre-wrap}.list{display:grid;gap:10px}.row{background:white;padding:13px;border:1px solid #e1eae4;border-radius:10px;overflow-wrap:anywhere}.row label{font-weight:600;display:flex;gap:8px;align-items:center}.row small{display:block;color:#8a9b92;margin:5px 0}.value{white-space:pre-wrap;max-height:150px;overflow:auto;font-size:12px;color:#466355}.foot{padding:16px;background:#fff;border-top:1px solid #e1eae4}.foot button{width:100%}.foot p{font-size:11px;color:#83988b;margin:8px 0 0}.help{font-size:12px;color:#7e9286;margin:13px 0}input{accent-color:#087e70} [hidden]{display:none!important}</style><div class="launch"><button class="fab scan-launch">扫描给 Codex</button> <button class="fab">填写简历</button></div><section class="drawer" hidden><div class="head"><div><strong>简历填写助手</strong><small>当前页面 · 本地资料 · 不自动提交</small></div><button class="light close" aria-label="收起">×</button></div><div class="body"><div class="actions"><button class="scan">扫描给 Codex</button><button class="light manage">资料 / 连接设置</button></div><p class="help">扫描会把当前表单及匹配的本地资料提供给 Codex；先展开分区；你也可在对话中授权 Codex 按本次计划填写。</p><div class="status" role="status">点击扫描，读取本页面的实际字段。</div><div class="list"></div></div><div class="foot"><button class="fill" disabled>授权并填写所选项目</button><p>只补充勾选的空白项；保存与最终提交由你完成。</p></div></section>`;
 const $=s=>root.querySelector(s);let plan=null,busy=false,timer,shareAuthorized=false;const send=async m=>{const r=await chrome.runtime.sendMessage(m);if(!r)throw Error('扩展已更新，请点击工具栏插件图标重新打开助手，无需刷新表单');if(r.error)throw Error(r.error);return r.data;};
 function render(p){plan=p;$('.list').replaceChildren();$('.fill').disabled=!p?.entries.some(e=>e.status==='ready');if(!p)return;const ready=p.entries.filter(e=>e.status==='ready').length;$('.status').textContent=`可填写 ${ready} 项 · 保留 ${p.entries.filter(e=>e.status==='preserve').length} 项 · 待补充 ${p.entries.filter(e=>['missing','manual'].includes(e.status)).length} 项`;
 if(p.coverage)$('.status').textContent+=`\n附件 ${p.coverage.attachments} 项 · 自定义控件 ${p.coverage.customControls} 项 · 未标注 ${p.coverage.unlabeled} 项`;if(p.limitations?.length)$('.status').textContent+='\n'+p.limitations.join('；');
 if(p.entries.length<=1&&p.entries.some(e=>/搜索/.test(e.label))){$('.status').textContent='当前是搜索页面，请进入岗位申请表后重新扫描。';$('.fill').disabled=true;}
 for(const e of p.entries){const row=document.createElement('div');row.className='row';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=e.status==='ready';check.disabled=e.status!=='ready';check.dataset.field=e.fieldId;label.append(check,document.createTextNode(e.label));const source=document.createElement('small');source.textContent=[e.section,e.status==='ready'?'本地资料匹配':e.reason].filter(Boolean).join(' · ');const value=document.createElement('div');value.className='value';value.textContent=e.status==='ready'?e.value:e.status==='preserve'?'已填写，保持原样':'留给你补充';row.append(label,source,value);
 if(e.kind==='file'){const picker=document.createElement('input');picker.type='file';picker.accept=e.accept||'';const upload=document.createElement('button');upload.textContent='授权上传所选文件';upload.disabled=true;picker.onchange=()=>upload.disabled=!picker.files.length;upload.onclick=async event=>{if(!event.isTrusted||!picker.files[0]||busy)return;const file=picker.files[0];if(file.size>10*1024*1024){value.textContent='文件大于10MB';return;}busy=true;upload.disabled=true;try{const bytes=new Uint8Array(await file.arrayBuffer());let data='';for(let i=0;i<bytes.length;i+=8192)data+=String.fromCharCode(...bytes.subarray(i,i+8192));const r=await send({type:'resume-upload',snapshotId:p.snapshotId,fieldId:e.fieldId,file:{name:file.name,type:file.type,lastModified:file.lastModified,base64:btoa(data)}});value.textContent=r.message;}catch(err){value.textContent=err.message;}finally{busy=false;}};row.append(picker,upload);}
 source.textContent+= ' · '+({upload:'图片 / 附件',date:'日期',select:'选项',text:'文字'}[e.action]||e.kind||'字段');$('.list').append(row);}}
 async function scan(commandId){if(busy)return;busy=true;$('.scan').disabled=true;$('.status').textContent='正在扫描当前页面并匹配本地资料…';try{render(await send({type:'resume-scan',commandId,shareWithCodex:shareAuthorized}));}catch(e){$('.status').textContent=e.message;}finally{busy=false;$('.scan').disabled=false;}}
 async function poll(){if(!host.isConnected){clearInterval(timer);return;}if(busy||$('.drawer').hidden)return;try{const r=await send({type:'resume-poll'});for(const c of r.commands){if(c.type==='scan')await scan(c.id);if(c.type==='review')render(await send({type:'resume-plan'}));if(c.type==='fill'){busy=true;try{const report=await send({type:'resume-fill',planId:c.planId,fieldIds:c.fieldIds});$('.status').textContent=`Codex计划已执行：回读确认 ${report.results.filter(x=>x.status==='verified').length} 项，待检查 ${report.results.filter(x=>x.status!=='verified').length} 项。未提交。`;plan=null;$('.fill').disabled=true;}catch(e){$('.status').textContent=e.message;}finally{busy=false;}}}}catch(e){$('.status').textContent='连接中断：'+e.message;}}
 function open(){ $('.drawer').hidden=false;$('.launch').hidden=true;clearInterval(timer);timer=setInterval(poll,1500);}
 root.querySelectorAll('.fab')[1].onclick=e=>{if(e.isTrusted)open();};$('.scan-launch').onclick=e=>{if(e.isTrusted){shareAuthorized=true;open();scan();}};$('.close').onclick=()=>{$('.drawer').hidden=true;$('.launch').hidden=false;clearInterval(timer);};
 $('.scan').onclick=e=>{if(e.isTrusted){shareAuthorized=true;scan();}};$('.manage').onclick=async e=>{if(e.isTrusted)try{await send({type:'resume-manage'});}catch(err){$('.status').textContent=err.message;}};
 $('.fill').onclick=async e=>{if(!e.isTrusted||!plan||busy)return;const ids=[...root.querySelectorAll('input:checked')].map(x=>x.dataset.field);if(!ids.length)return;busy=true;$('.fill').disabled=true;try{const report=await send({type:'resume-fill',planId:plan.id,fieldIds:ids});$('.status').textContent=`回读确认 ${report.results.filter(x=>x.status==='verified').length} 项，待检查 ${report.results.filter(x=>x.status!=='verified').length} 项。未提交。`;for(const r of report.results){const c=[...root.querySelectorAll('input')].find(x=>x.dataset.field===r.fieldId);if(c){c.disabled=true;c.parentElement.parentElement.querySelector('small').textContent=r.status==='verified'?'已填写并回读确认':'需检查：'+r.status;}}plan=null;}catch(err){$('.status').textContent=err.message;}finally{busy=false;}};
 globalThis.__resumeWidget={version:'0.3.1',runtime:chrome.runtime,open,destroy(){clearInterval(timer);host.remove();}};
})();
