(()=>{
 if(globalThis.__resumeWidget){globalThis.__resumeWidget.open();return;}
 const host=document.createElement('div');host.id='resume-companion-local';host.style.cssText='all:initial;position:fixed;right:20px;bottom:90px;z-index:2147483646';
 const root=host.attachShadow({mode:'closed'});document.documentElement.append(host);
 root.innerHTML=`<style>:host{all:initial}*{box-sizing:border-box}button,input{font:inherit}button{cursor:pointer;border:0;border-radius:9px;padding:10px 15px;background:#087e70;color:#fff;font-weight:600}button:disabled{background:#c5d7d1;cursor:default}.fab{box-shadow:0 5px 24px #164e4340;padding:14px 20px;font:600 15px 'Microsoft YaHei',sans-serif}.drawer{font:14px/1.6 'Microsoft YaHei',sans-serif;position:fixed;right:16px;top:18px;bottom:18px;width:min(460px,calc(100vw - 32px));background:#f6f9f7;border:1px solid #d7e6df;border-radius:18px;box-shadow:0 10px 60px #17352f33;color:#243e35;display:flex;flex-direction:column;overflow:hidden}.head{padding:20px;background:white;display:flex;justify-content:space-between;align-items:center}.head strong{font-size:18px}.head small{display:block;color:#789187;font-size:11px}.light{background:#eaf2ed;color:#41715d}.body{padding:18px;overflow:auto;flex:1}.actions{display:flex;gap:8px;flex-wrap:wrap}.status{padding:12px 0;color:#537864;white-space:pre-wrap}.list{display:grid;gap:10px}.row{background:white;padding:13px;border:1px solid #e1eae4;border-radius:10px;overflow-wrap:anywhere}.row label{font-weight:600;display:flex;gap:8px;align-items:center}.row small{display:block;color:#8a9b92;margin:5px 0}.value{white-space:pre-wrap;max-height:150px;overflow:auto;font-size:12px;color:#466355}.foot{padding:16px;background:#fff;border-top:1px solid #e1eae4}.foot button{width:100%}.foot p{font-size:11px;color:#83988b;margin:8px 0 0}.help{font-size:12px;color:#7e9286;margin:13px 0}input{accent-color:#087e70} [hidden]{display:none!important}</style><button class="fab">▤ 填写简历</button><section class="drawer" hidden><div class="head"><div><strong>简历填写助手</strong><small>当前页面 · 本地资料 · 不自动提交</small></div><button class="light close" aria-label="收起">×</button></div><div class="body"><div class="actions"><button class="scan">扫描当前表单</button><button class="light manage">资料 / 连接设置</button></div><p class="help">已有内容保留。先展开需要填写的分区，再扫描；下方核对后一次授权。</p><div class="status" role="status">点击扫描，读取本页面的实际字段。</div><div class="list"></div></div><div class="foot"><button class="fill" disabled>授权并填写所选项目</button><p>只补充勾选的空白项；保存与最终提交由你完成。</p></div></section>`;
 const $=s=>root.querySelector(s);let plan=null,busy=false,timer;const send=async m=>{const r=await chrome.runtime.sendMessage(m);if(!r)throw Error('扩展已更新，请刷新网页再打开助手');if(r.error)throw Error(r.error);return r.data;};
 function render(p){plan=p;$('.list').replaceChildren();$('.fill').disabled=!p?.entries.some(e=>e.status==='ready');if(!p)return;const ready=p.entries.filter(e=>e.status==='ready').length;$('.status').textContent=`可填写 ${ready} 项 · 保留 ${p.entries.filter(e=>e.status==='preserve').length} 项 · 待补充 ${p.entries.filter(e=>['missing','manual'].includes(e.status)).length} 项`;
 if(p.entries.length<=1&&p.entries.some(e=>/搜索/.test(e.label))){$('.status').textContent='当前是搜索页面，请进入岗位申请表后重新扫描。';$('.fill').disabled=true;}
 for(const e of p.entries){const row=document.createElement('div');row.className='row';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=e.status==='ready';check.disabled=e.status!=='ready';check.dataset.field=e.fieldId;label.append(check,document.createTextNode(e.label));const source=document.createElement('small');source.textContent=[e.section,e.status==='ready'?'本地资料匹配':e.reason].filter(Boolean).join(' · ');const value=document.createElement('div');value.className='value';value.textContent=e.status==='ready'?e.value:e.status==='preserve'?'已填写，保持原样':'留给你补充';row.append(label,source,value);$('.list').append(row);}}
 async function scan(commandId){if(busy)return;busy=true;$('.scan').disabled=true;$('.status').textContent='正在扫描当前页面并匹配本地资料…';try{render(await send({type:'resume-scan',commandId}));}catch(e){$('.status').textContent=e.message;}finally{busy=false;$('.scan').disabled=false;}}
 async function poll(){if(busy||$('.drawer').hidden)return;try{const r=await send({type:'resume-poll'});for(const c of r.commands){if(c.type==='scan')await scan(c.id);if(c.type==='review')render(await send({type:'resume-plan'}));}}catch{}}
 function open(){ $('.drawer').hidden=false;$('.fab').hidden=true;clearInterval(timer);timer=setInterval(poll,1500);}
 $('.fab').onclick=e=>{if(e.isTrusted)open();};$('.close').onclick=()=>{$('.drawer').hidden=true;$('.fab').hidden=false;clearInterval(timer);};
 $('.scan').onclick=e=>{if(e.isTrusted)scan();};$('.manage').onclick=async e=>{if(e.isTrusted)try{await send({type:'resume-manage'});}catch(err){$('.status').textContent=err.message;}};
 $('.fill').onclick=async e=>{if(!e.isTrusted||!plan||busy)return;const ids=[...root.querySelectorAll('input:checked')].map(x=>x.dataset.field);if(!ids.length)return;busy=true;$('.fill').disabled=true;try{const report=await send({type:'resume-fill',planId:plan.id,fieldIds:ids});$('.status').textContent=`回读确认 ${report.results.filter(x=>x.status==='verified').length} 项，待检查 ${report.results.filter(x=>x.status!=='verified').length} 项。未提交。`;for(const r of report.results){const c=[...root.querySelectorAll('input')].find(x=>x.dataset.field===r.fieldId);if(c){c.disabled=true;c.parentElement.parentElement.querySelector('small').textContent=r.status==='verified'?'已填写并回读确认':'需检查：'+r.status;}}plan=null;}catch(err){$('.status').textContent=err.message;}finally{busy=false;}};
 globalThis.__resumeWidget={open};
})();
