import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root=fileURLToPath(new URL('../',import.meta.url));
export async function engineBundle(directory=root) {
  const entry=(await fs.readFile(path.join(directory,'src/autofill/engine-entry.js'),'utf8')).replace(/\r\n/g,'\n');
  const catalog=(await fs.readFile(path.join(directory,'src/autofill/component-catalog.mjs'),'utf8')).replace(/\r\n/g,'\n');
  const driver=(await fs.readFile(path.join(directory,'src/autofill/select-driver.mjs'),'utf8')).replace(/\r\n/g,'\n');
  const marker='/* @component-catalog */';
  if(entry.split(marker).length!==2||!catalog.includes('export function createComponentCatalog('))throw Error('Invalid engine source boundary');
  if(entry.split('/* @select-driver */').length!==2||!driver.includes('export function createSelectDriver('))throw Error('Invalid driver source boundary');
  const body=entry.replace(marker,catalog.replace('export function createComponentCatalog(','function createComponentCatalog(')).replace('/* @select-driver */',driver.replace('export function createSelectDriver(','function createSelectDriver('));
  const digest=createHash('sha256').update(entry+'\0'+catalog+'\0'+driver).digest('hex');
  return '// Generated by scripts/build-engine.mjs; edit src/autofill, not this file.\n// source-sha256: '+digest+'\n'+body;
}
export async function checkEngine(directory=root) {
  const expected=await engineBundle(directory),actual=await fs.readFile(path.join(directory,'extension/engine.js'),'utf8');
  if(expected!==actual.replace(/\r\n/g,'\n'))throw Error('Engine bundle differs from reviewed sources; run npm run build:engine');
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)) {
  if(process.argv.includes('--check'))await checkEngine();
  else await fs.writeFile(path.join(root,'extension/engine.js'),await engineBundle());
}
